Feat/add editor form puzzle
CraftZoo/treashunt pull request #34
Opened 2022-12-12 19:37 UTC by Netoun

2022-12-13 11:22 UTC, sylvainDNS requested changes

2022-12-13 11:22 UTC, sylvainDNS commented on app/routes/admin/puzzles/$puzzleId.tsx
> +  console.log(puzzle)
```suggestion
```

2022-12-13 11:22 UTC, sylvainDNS commented on app/routes/admin/puzzles/$puzzleId.tsx
> +      <Heading mb={8}>Modifier une enigme</Heading>
ça prend quel tag par défaut ?

2022-12-13 11:22 UTC, sylvainDNS commented on app/theme/theme.ts
> +      background: '#F1FAFF',
variable ?

2022-12-13 11:22 UTC, sylvainDNS commented on prisma/schema.prisma
> +  provider = "postrges"
?

2022-12-13 11:22 UTC, sylvainDNS commented
Pense aussi à supprimer `prisma/dev.db`, je l'ai enlevé du gitignore et elle se retrouve dans ton commit

2022-12-13 13:28 UTC, Netoun commented on prisma/schema.prisma
> +  provider = "postrges"
C une nouvelle base hyper puissante

2022-12-13 14:51 UTC, Netoun commented on app/routes/admin/puzzles/$puzzleId.tsx
> +      <Heading mb={8}>Modifier une enigme</Heading>
h2

2022-12-13 23:19 UTC, sylvainDNS commented on app/components/atoms/Link.tsx
> +type LinkComponent = ChakraComponent<'a', {}>
Impossible d'utiliser la prop `to` si on fait comme ça

2022-12-14 10:31 UTC, sylvainDNS requested changes

2022-12-14 10:31 UTC, sylvainDNS commented on app/components/molecules/PuzzleUpsertForm.tsx
> +    const form = event.target as HTMLFormElement
`as`utile comme défini au dessus ?

2022-12-14 10:31 UTC, sylvainDNS commented on app/components/organisms/ConnectedPuzzleUpsertForm.tsx
> +  return json({ success: `L'enigme a bien ete mise à jour` })
```suggestion
  return json({ success: "L'énigme a été mise à jour" })
```

2022-12-14 10:38 UTC, Netoun commented on app/components/molecules/PuzzleUpsertForm.tsx
> +    const form = event.target as HTMLFormElement
Oui

2022-12-14 19:59 UTC, sylvainDNS approved these changes

2022-12-14 20:13 UTC, merged