improve app components tree folder
CraftZoo/treashunt pull request #59
Opened 2022-12-24 15:45 UTC by Netoun

2022-12-26 09:17 UTC, sylvainDNS requested changes
je vais faire une PR pour inclure le typechecking dans la ci

2022-12-26 09:17 UTC, sylvainDNS commented on app/components/molecules/Puzzle/PuzzleForm.tsx
> +  | { mode: 'creation'; puzzle?: CreatePuzzle }
ça fonctionne ça ? en création on ne doit pas passer de puzzle

2022-12-26 09:17 UTC, sylvainDNS commented on app/components/molecules/Puzzle/PuzzleForm.tsx
> +    id: mode === 'update' ? puzzle.id : '',
```suggestion
    id: isUpdate ? puzzle.id : '',
```

2022-12-26 09:17 UTC, sylvainDNS commented on tsconfig.json
> +  "include": ["remix.env.d.ts", "**/*.ts", "**/*.tsx", "app/routes/puzzlestsx"],
?

2022-12-26 09:25 UTC, sylvainDNS commented on app/components/molecules/Puzzle/PuzzleForm.tsx
> +  | { mode: 'creation'; puzzle?: CreatePuzzle }
L'intéret de `never` c'est que ça nous empêche de passe en prop un puzzle quand on est en mode création (puisque le puzzle n'existe pas). Là c'est possible de faire ça ⬇️ 

```tsx
  import { Prisma } from '@prisma/client'

import PuzzleForm from '~/components/molecules/Puzzle/PuzzleForm'

export { action } from '~/components/molecules/Puzzle/PuzzleForm'

const PuzzleCreation = () => {
  return (
    <PuzzleForm
      mode="creation"
      puzzle={{
        answer: '',
        authorId: '',
        coordinates: {
          latitude: new Prisma.Decimal(1),
          longitude: new Prisma.Decimal(1),
        },
        question: '',
        subtitle: '',
        title: '',
      }}
    />
  )
}

export default PuzzleCreation
```

2022-12-27 22:15 UTC, Netoun commented on app/components/molecules/Puzzle/PuzzleForm.tsx
> +  | { mode: 'creation'; puzzle?: CreatePuzzle }
Oui, je vois pas en quoi c'est genant. En soit en creation on peut potentiellement alimente le form

2022-12-27 22:18 UTC, Netoun commented on app/components/molecules/Puzzle/PuzzleForm.tsx
> +    id: mode === 'update' ? puzzle.id : '',
Si je fais ca il prend pas le bon type sur ``puzzle

2022-12-28 17:03 UTC, sylvainDNS commented on app/components/molecules/Puzzle/PuzzleForm.tsx
> +    id: mode === 'update' ? puzzle.id : '',
c'est chelou

2022-12-28 17:04 UTC, sylvainDNS approved these changes

2022-12-28 17:27 UTC, merged