Feat/user management
CraftZoo/treashunt pull request #83
Opened 2023-01-21 23:33 UTC by sylvainDNS

![image](https://user-images.githubusercontent.com/16577439/213894135-353ba001-c370-4602-9051-c5990c4260ab.png)
![image](https://user-images.githubusercontent.com/16577439/213894140-415d16cb-32fb-4c9b-b731-859104bcc8c0.png)

2023-01-22 12:45 UTC, Netoun requested changes
Super travail Sylvain ! <3

2023-01-22 12:45 UTC, Netoun commented on app/components/atoms/DialogClose.tsx
> +  <Link {...props}>
Pourquoi ne pas utiliser : https://chakra-ui.com/docs/components/close-button ?

2023-01-22 12:45 UTC, Netoun commented on app/components/atoms/PasswordInput.tsx
> +interface InputProps extends Omit<ChakraInputProps, 'isRequired'> {
Pourquoi juste remplace la props `isRequired` par `required`

2023-01-22 12:45 UTC, Netoun commented on app/routes/admin/users/delete.$userId.tsx
> +import DialogOverlay from '~/components/atoms/DialogOverlay'
Pour eviter pleins d'import et dans ce cas precis, je ferai un dossier modal dans atoms  et  j'exporterai tout dans un index

2023-01-22 12:45 UTC, Netoun commented on app/routes/admin/users/delete.$userId.tsx
> +import DialogOverlay from '~/components/atoms/DialogOverlay'
Et j'imagine du coup que tu as refais tout a la main car la dialog de chakra ne marchait pas avec ta facon de faire ?

2023-01-22 12:45 UTC, Netoun commented on app/routes/admin/users/add.tsx
> +const UserFields = z.object({
J'utilise ça comme convention pour mes schemas zod mais comme tu veux

```suggestion
const userAddSchema= z.object({})
type UserAddSchema = z.infer<typeof userAddSchema>
type UserAddSchemaErrors = inferSafeParseErrors<typeof UserAddSchema>
```

2023-01-22 12:45 UTC, Netoun commented on app/routes/admin/users.tsx
> +        <TableContainer>
Etire le tableau, pas tres beau sur un ecran classique, et tu peux rajouter la date de creation

![image](https://user-images.githubusercontent.com/22615645/213915986-8b731802-e6c2-4e02-b4c1-1b8a29b85000.png)

2023-01-22 12:45 UTC, Netoun commented on app/routes/admin/users/add.tsx
> +              </FormControl>
Il faut une confirmation de password

2023-01-22 12:45 UTC, Netoun commented on app/routes/admin/users/add.tsx
> +                </RadioGroup>
A mettre plus dans un select, a terme il faudrait :

- admin
- editeur
- lecteur

2023-01-22 19:09 UTC, sylvainDNS commented on app/routes/admin/users/delete.$userId.tsx
> +import DialogOverlay from '~/components/atoms/DialogOverlay'
Oui impossible avec la dialog de chakra

2023-01-22 19:10 UTC, sylvainDNS commented on app/routes/admin/users/add.tsx
> +                </RadioGroup>
Yep on verra à ce moment là

2023-01-22 19:44 UTC, Netoun commented on app/routes/admin/users/add.tsx
> +                </RadioGroup>
Oui mais tu peux deja mettre le select :)

2023-01-23 17:45 UTC, sylvainDNS commented on app/routes/admin/users/add.tsx
> +                </RadioGroup>
c'est pas une bonne pratique pour 2 options !!!!!!!!!!!!!!!!!!!!!

2023-01-23 17:56 UTC, sylvainDNS commented on app/components/atoms/DialogClose.tsx
> +  <Link {...props}>
trop relou à typer

2023-01-23 17:56 UTC, sylvainDNS commented on app/components/atoms/PasswordInput.tsx
> +interface InputProps extends Omit<ChakraInputProps, 'isRequired'> {
?

2023-01-23 18:07 UTC, sylvainDNS commented on app/routes/admin/users.tsx
> +        <TableContainer>
C'est pas une bonne chose d'étirer sur tout l'écran, il vaut mieux centrer le contenu c'est plus facile à lire

2023-01-24 16:40 UTC, Netoun commented on app/routes/admin/users/add.tsx
> +                </RadioGroup>
t'enerves pas

2023-01-24 16:42 UTC, Netoun commented on app/components/atoms/PasswordInput.tsx
> +interface InputProps extends Omit<ChakraInputProps, 'isRequired'> {
Ici tu omits isRequired, pour remettre en dessous un ``required

puis apres tu remets : 
`        isRequired={required}`

2023-01-26 17:52 UTC, sylvainDNS commented on app/components/atoms/PasswordInput.tsx
> +interface InputProps extends Omit<ChakraInputProps, 'isRequired'> {
j'ai simplifié, mais je veux forcer l'utilisation de `required` pour que ce soit le navigateur qui le gère

2023-01-27 18:38 UTC, Netoun commented on app/routes/admin/users/add.tsx
> +          </Form>
tu veux pas mettre le form dans un composant ?

2023-01-29 18:20 UTC, sylvainDNS commented on app/routes/admin/users/add.tsx
> +          </Form>
On peut, je trouve qu'on abstrait trop mais comme tu le sens

2023-01-30 19:22 UTC, Netoun requested changes

2023-01-31 14:05 UTC, sylvainDNS commented on app/components/atoms/Dialog.tsx
> +const Dialog = ({ onClose, children }: DialogProps) => {
mais non j'ai le droit ?????????????????????

2023-01-31 14:07 UTC, sylvainDNS commented on app/components/atoms/Dialog.tsx
> +const Dialog = ({ onClose, children }: DialogProps) => {
IMHO l'idéal serait d'utiliser des compounds component mais ça casse la convention de Cacra 💩

2023-02-01 09:12 UTC, Netoun commented on app/components/atoms/Dialog.tsx
> +const Dialog = ({ onClose, children }: DialogProps) => {
Tu l'as deja fait ailleurs donc tu peux

2023-02-07 20:14 UTC, Netoun approved these changes

2023-02-07 20:14 UTC, Netoun commented on app/routes/admin/users/add.tsx
> +    <Dialog.Root onClose={handleClose}>
Pourquoi pas mettre directement dans le index pour juste avoir `Dialog` ?

2023-02-07 20:14 UTC, Netoun commented on app/routes/admin/users/add.tsx
> +    <Dialog.Root onClose={handleClose}>
De plus, concernant le nom des fichiers dans Dialog, j'aurai prefix quand meme par :

- index.tsx
- DialogBody.tsx
- DialogHeader.tsx
...etc

Puis exporter sans les prefixes dans l'index
Ca permet d'eviter d'avoir de flood l'autocompletion d'import dans le projet
Mais on peut garde comme ca

2023-02-07 20:14 UTC, Netoun commented on app/components/molecules/Sidebar/SidebarMenu.tsx
> +      ) : null}
?

2023-02-07 21:13 UTC, sylvainDNS commented on app/routes/admin/users/add.tsx
> +    <Dialog.Root onClose={handleClose}>
hold my beer

2023-02-07 21:14 UTC, sylvainDNS commented
?

2023-02-07 21:39 UTC, Netoun commented on app/routes/admin/users.tsx
> +                    ) : null}
Ici

2023-02-07 21:49 UTC, Netoun approved these changes

2023-02-07 21:50 UTC, merged